### ISSUE TITLE
Line Equation is wrong

### ISSUE THREAD

**Issue by tybbmaq** [amzn/computer-vision-basics-in-microsoft-excel#1]
Line Equation   **x*sin(θ) + y*cos(θ) = r** is wrong, it should be  **x*cos(θ) + y*sin(θ) = r**

**Comment by alokgovil** [comment]
Thanks tybbmaq for reporting the issue.

The equation has been corrected in multiple sheets, across the relevant .xlsx files.  The equations actually used in the Excel formulas have already been correct.

Sorry for my miss on this.  Issues like this are not typical of me.  I'm just getting old, I guess.  :-)
